import { ReactComponent as IconDislike } from '../assets/icon/dislike.svg';
import { ReactComponent as IconLike } from '../assets/icon/like.svg';
import { ReactComponent as IconNext } from '../assets/icon/next.svg';
import { ReactComponent as IconNote } from '../assets/icon/note.svg';
import { ReactComponent as IconPlay } from '../assets/icon/play.svg';
import { ReactComponent as IconStop } from '../assets/icon/stop.svg';
import { ReactComponent as IconPrev } from '../assets/icon/prev.svg';
import { ReactComponent as IconRepeat } from '../assets/icon/repeat.svg';
import { ReactComponent as IconSearch } from '../assets/icon/search.svg';
import { ReactComponent as IconShuffle } from '../assets/icon/shuffle.svg';
import { ReactComponent as IconSprite } from '../assets/icon/sprite.svg';
import { ReactComponent as IconVolume } from '../assets/icon/volume.svg';
import { ReactComponent as IconLogout } from '../assets/icon/logout.svg';
import { ReactComponent as VolumeBar } from '../assets/icon/volumeBar.svg';
import { ReactComponent as IconWatch } from '../assets/icon/watch.svg';

export const Icon = ({ name, className }) => {
  if (name === 'dislike') return <IconDislike className={className} />;
  if (name === 'like') return <IconLike className={className} />;
  if (name === 'next') return <IconNext className={className} />;
  if (name === 'note') return <IconNote className={className} />;
  if (name === 'play') return <IconPlay className={className} />;
  if (name === 'stop') return <IconStop className={className} />;
  if (name === 'prev') return <IconPrev className={className} />;
  if (name === 'watch') return <IconWatch className={className} />;
  if (name === 'repeat') return <IconRepeat className={className} />;
  if (name === 'search') return <IconSearch className={className} />;
  if (name === 'shuffle') return <IconShuffle className={className} />;
  if (name === 'sprite') return <IconSprite className={className} />;
  if (name === 'volume') return <IconVolume className={className} />;
  if (name === 'logout') return <IconLogout className={className} />;
  if (name === 'volumeBar') return <VolumeBar className={className} />;
};
